ALTER TABLE votacao.sessoes ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE votacao.pautas ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE votacao.votos ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
